homepage: "https://poi.apache.org/"
language: jvm
main_repo: "https://github.com/apache/poi.git"
fuzzing_engines:
  - libfuzzer
sanitizers:
  - address
# https://www.jacoco.org/jacoco/trunk/doc/agent.html
coverage_extra_args: includes=org.apache.poi.*:org.apache.xmlbeans.*
vendor_ccs:
  - "wagner@code-intelligence.com"
  - "yakdan@code-intelligence.com"
  - "glendowne@code-intelligence.com"
  - "patrice.salathe@code-intelligence.com"
  - "hlin@code-intelligence.com"
  - "schaich@code-intelligence.com"
  - "bug-disclosure@code-intelligence.com"
  - "centic@apache.org"
  - "dominik.stadler@gmail.com"